
version: '3.4'
services:
    app:
        build:
            dockerfile: ${D_PATH:-Dockerfile}
            context: .
        depends_on:
            - mongo
        ports:
            -  ${SERVICE_PORT:-8000}:80
        environment:
            - ENV=${ENV:-debug}
            - WEB_API_PORT=${WEB_API_PORT:-80}
            - WEB_API_BASE_URL=${WEB_API_BASE_URL:-0.0.0.0}
            # Mongo config
            - MONGO_URI=mongodb://${MONGO_USER:-u}:${MONGO_PASSWORD:-p}@mongo:${DBPORT:-27017}
            - MONGO_DB=${MONGO_DB_NAME:-db}
            - APP_ENV=${APP_ENV:-debug}
        volumes:
            - ./:/go/src
    mongo:
        container_name: mongo
        image: mongo:4.4.5
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-u}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-p}
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-db}
volumes:
  mongodb: 