
version: '3.4'
services:
    app:
        build:
            dockerfile: ${D_PATH:-Dockerfile}
            context: .
        depends_on:
            - mongodb
        ports:
            -  ${SERVICE_PORT:-8000}:80
        environment:
            - WEB_API_PORT=${WEB_API_PORT:-80}
            - WEB_API_BASE_URL=${WEB_API_BASE_URL:-0.0.0.0}

            - ENV=debug
        volumes:
            - ./:/go/src
    mongodb:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db
volumes:
  mongodb: 